### ISSUE TITLE
fix storybook 

### ISSUE THREAD

**Issue by dominikg** [vitejs/vite-ecosystem-ci#130]
storybook changed the repository layout for vite-builder and package.json no longer is in root of the repo but in `packages/vite-builder`  

causing an error in the test https://github.com/vitejs/vite-ecosystem-ci/actions/runs/3202468586/jobs/5231480918#step:7:269

Possible fixes:
1) add support for custom package.json paths in vite-ecosystem-ci
2) switch to storybook 7 monorepo

**Comment by JReinhold** [comment]
Just to add some context here.
In Storybook 7.0 (currently alpha), the Vite builder is being pulled into the Storybook monorepo, and is located at

https://github.com/storybookjs/storybook/tree/next/code/lib/builder-vite

I don't know if you want to hold off testing against 7.0 until it's released though.

**Comment by dominikg** [comment]
the storybook monorepo seems to have a very custom layout, what is `yarn task` for example. (seen in the root package.json) and there doesn't seem to be build or test scripts in the builder-vite subdirectory and other scripts link to parent directories.

So it looks like we have to checkout the whole storybook repo. To avoid doing a lot of extra work and a very long test runtime it would be great if you found a way to build and test builder-vite only.

Is that currently possible or will it be possible?

**Comment by dominikg** [comment]
fixed by #311
